'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { useAuthUser } from '@/hooks/useAuthUser';
import { getAuthClient } from '@/lib/auth/client';
import type { Order } from '@/lib/store/types';
import { orderStatus } from '@/lib/admin/client';
import { adminCopy } from '@/content/admin';
import { formatPrice } from '@/lib/store/price';
import { checkoutCopy as copy,storeCopy } from '@/content/store';
import { Spinner,Toast,BUTTON } from './StoreUI';
export function OrdersPanel(){const {user,loading}=useAuthUser();const [orders,setOrders]=useState<Order[]>([]);const [pending,setPending]=useState(true);const [owner,setOwner]=useState('');const [error,setError]=useState('');useEffect(()=>{let active=true;if(!user)return;getAuthClient().from('orders').select('id,status,total,created_at,shipping_address,shipping_cost,payment_status,tracking_reference,order_items(product_id,product_name,quantity,unit_price)').eq('user_id',user.id).order('created_at',{ascending:false}).then(({data,error})=>{if(active){if(error)setError(copy.orderLoadError);else setOrders((data??[]) as Order[]);setOwner(user.id);setPending(false);}});return()=>{active=false;};},[user]);if(loading||user&&(pending||owner!==user.id))return <Spinner label={copy.loading}/>;return <section className="shell pb-20 pt-36 lg:pt-44"><h1 className="text-display-sm">{copy.ordersTitle}</h1><div className="mt-10"><Toast message={error} error/>{!user?<Link href="/iniciar-sesion" className={`${BUTTON} border border-accent-cyan text-accent-cyan`}>{copy.login}</Link>:orders.length?<ul className="space-y-6">{orders.map(order=><li key={order.id} className="border border-border-editorial p-5 sm:p-8"><div className="flex flex-wrap justify-between gap-4"><h2 className="font-mono text-xl">{order.id.slice(0,8).toUpperCase()}</h2><span className="text-sm text-amber-300">{orderStatus(order.status)}</span></div><ul className="mt-5 space-y-3">{order.order_items?.map(item=><li key={item.product_id} className="flex justify-between gap-4 text-sm"><span>{item.product_name} × {item.quantity}</span><span className="shrink-0 tabular-nums">{formatPrice(item.unit_price*item.quantity)}</span></li>)}</ul><p className="mt-5 font-medium tabular-nums">{formatPrice(Number(order.total)+Number(order.shipping_cost??0))}</p><p className="mt-2 text-sm text-text-secondary">{order.shipping_cost==null?adminCopy.shippingPending:adminCopy.grandTotal} · {adminCopy.payments[order.payment_status as keyof typeof adminCopy.payments]??copy.orderPending}</p>{order.tracking_reference?<p className="mt-2 text-sm">{adminCopy.tracking}: {order.tracking_reference}</p>:null}<p className="mt-3 text-sm text-text-secondary">{order.shipping_address.shippingMethod==='lima_delivery'?`${copy.address}: ${order.shipping_address.street}, ${order.shipping_address.district}`:`${copy.pickup} ${order.shipping_address.pickupPointName}`}</p></li>)}</ul>:!error?<p className="text-text-secondary">{copy.noOrders}</p>:null}<Link href="/tienda" className={`${BUTTON} mt-8 border border-border-editorial text-accent-cyan`}>{storeCopy.continueShopping}</Link></div></section>;}
