'use client';
import { useState,type FormEvent } from 'react';
import { adminCopy as copy } from '@/content/admin';
import { pickupDepartments,peruLocations,resolvePeruLocation,isLimaMetropolitanaDistrict } from '@/lib/peru-ubigeo';
import { adminMutate,adminError } from '@/lib/admin/client';
import type { AdminPoint } from '@/lib/admin/types';
import { Button,Input,Select,Field,Toast } from '@/components/store/StoreUI';
export function PickupEditor({point,onSaved,onClose}:{point:AdminPoint|null;onSaved:()=>void;onClose:()=>void}) {
 const [department,setDepartment]=useState(point?.ubigeo.slice(0,2)??'');const [province,setProvince]=useState(point?.ubigeo.slice(0,4)??'');const [ubigeo,setUbigeo]=useState(point?.ubigeo??'');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const provinces=[...new Map(peruLocations.filter(loc=>loc.ubigeo.startsWith(department)&&!isLimaMetropolitanaDistrict(loc.ubigeo)).map(loc=>[loc.ubigeo.slice(0,4),{code:loc.ubigeo.slice(0,4),name:loc.province}])).values()];const districts=peruLocations.filter(loc=>loc.ubigeo.startsWith(province)&&!isLimaMetropolitanaDistrict(loc.ubigeo));
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);const id=String(f.get('id')??'').trim();if(!/^[a-z0-9-]{1,80}$/.test(id)||!resolvePeruLocation(ubigeo)||isLimaMetropolitanaDistrict(ubigeo)){setError(copy.invalidPoint);return;}setBusy(true);setError('');try{await adminMutate('pickup_save',{id,version:point?.version??0,name:String(f.get('name')??'').trim(),street:String(f.get('street')??'').trim(),reference:String(f.get('reference')??'').trim(),hours:String(f.get('hours')??'').trim(),ubigeo,active:f.get('active')==='on'});onSaved();}catch(issue){setError(adminError(issue));}finally{setBusy(false);}}
 return <section className="border border-border-editorial bg-bg-secondary p-5 sm:p-8"><h3 className="text-2xl font-medium">{point?copy.edit:copy.newPoint}</h3><p className="mt-3 text-sm leading-relaxed text-text-secondary">{copy.pickupHint}</p><form onSubmit={save} className="mt-8 space-y-5"><Field id="point-id" label={copy.pointId}><Input id="point-id" name="id" required pattern="[a-z0-9-]+" maxLength={80} readOnly={Boolean(point)} defaultValue={point?.id??''} aria-describedby="point-id-hint"/></Field><p id="point-id-hint" className="text-sm text-text-secondary">{copy.pointIdHint}</p><Field id="point-name" label={copy.pointName}><Input id="point-name" name="name" maxLength={200} required defaultValue={point?.name??''}/></Field><div className="grid gap-5 sm:grid-cols-2"><Field id="point-department" label={copy.department}><Select id="point-department" value={department} required onChange={e=>{setDepartment(e.target.value);setProvince('');setUbigeo('');}}><option value="">{copy.select}</option>{pickupDepartments.map(d=><option key={d.code} value={d.code}>{d.name}</option>)}</Select></Field><Field id="point-province" label={copy.province}><Select id="point-province" value={province} required disabled={!department} onChange={e=>{setProvince(e.target.value);setUbigeo('');}}><option value="">{copy.select}</option>{provinces.map(p=><option key={p.code} value={p.code}>{p.name}</option>)}</Select></Field><Field id="point-district" label={copy.district}><Select id="point-district" value={ubigeo} required disabled={!province} onChange={e=>setUbigeo(e.target.value)}><option value="">{copy.select}</option>{districts.map(d=><option key={d.ubigeo} value={d.ubigeo}>{d.district}</option>)}</Select></Field></div><Field id="point-street" label={copy.pointStreet}><Input id="point-street" name="street" maxLength={250} required defaultValue={point?.street??''}/></Field><Field id="point-reference" label={copy.pointReference}><Input id="point-reference" name="reference" maxLength={250} required defaultValue={point?.reference??''}/></Field><Field id="point-hours" label={copy.hours}><Input id="point-hours" name="hours" maxLength={200} required defaultValue={point?.hours??''}/></Field><label className="flex min-h-12 items-center gap-3"><input name="active" type="checkbox" className="h-5 w-5 accent-cyan-500" defaultChecked={point?.active??false}/>{copy.pointActive}</label><Toast message={error} error/><Button disabled={busy} type="submit" className="w-full">{busy?copy.saving:copy.save}</Button><Button disabled={busy} type="button" variant="secondary" className="w-full" onClick={onClose}>{copy.cancel}</Button></form></section>;
}
