'use client';
import { useState,useRef,type FormEvent } from 'react';
import { adminCopy as copy } from '@/content/admin';
import { adminMutate,adminError } from '@/lib/admin/client';
import type { AdminProduct } from '@/lib/admin/types';
import { Button,Input,Field,Toast } from '@/components/store/StoreUI';
export function StockEditor({product,onSaved,onClose}:{product:AdminProduct;onSaved:()=>void;onClose:()=>void}) {
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const request=useRef<string|null>(null);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);const delta=Number(f.get('delta'));const reason=String(f.get('reason')??'').trim();if(!Number.isInteger(delta)||delta===0||Math.abs(delta)>999999||product.stock+delta<0||reason.length<3){setError(copy.invalidStock);return;}setBusy(true);setError('');request.current??=crypto.randomUUID();try{await adminMutate('stock_adjust',{id:product.id,version:product.version,delta,reason,request_id:request.current});onSaved();}catch(issue){setError(adminError(issue));}finally{setBusy(false);}}
 return <section className="border border-border-editorial bg-bg-secondary p-5 sm:p-8"><h3 className="text-2xl font-medium">{copy.stockTitle}</h3><p className="mt-3 text-accent-cyan">{product.name}</p><p className="mt-4 text-sm leading-relaxed text-text-secondary">{copy.stockHint}</p><dl className="mt-6 flex gap-10"><div><dt className="text-sm text-text-secondary">{copy.available}</dt><dd className="mt-2 text-2xl tabular-nums">{product.stock}</dd></div><div><dt className="text-sm text-text-secondary">{copy.reserved}</dt><dd className="mt-2 text-2xl tabular-nums">{product.reserved}</dd></div></dl><form onSubmit={save} onChange={()=>{request.current=null;}} className="mt-7 space-y-5"><Field id="stock-delta" label={copy.delta}><Input id="stock-delta" name="delta" type="number" min={-999999} max={999999} step={1} required/></Field><Field id="stock-reason" label={copy.reason}><Input id="stock-reason" name="reason" minLength={3} maxLength={250} required/></Field><p className="text-sm text-text-secondary">{copy.reasonHint}</p><Toast message={error} error/><Button disabled={busy} type="submit" className="w-full">{busy?copy.saving:copy.stockSave}</Button><Button disabled={busy} variant="secondary" type="button" className="w-full" onClick={onClose}>{copy.cancel}</Button></form></section>;
}
