/** Texto compartido de registro, acceso y seguridad de la cuenta. */
export const authCopy = {
  signUp: { title: 'Crea tu cuenta', lede: 'Tu acceso a la tienda de AFCRtecnologia.', action: 'Crear cuenta', alternate: '¿Ya tienes una cuenta?', link: 'Iniciar sesión' },
  signIn: { title: 'Bienvenido de nuevo', lede: 'Entra a tu cuenta para continuar.', action: 'Iniciar sesión', alternate: '¿Es tu primera visita?', link: 'Crear una cuenta' },
  recovery: { title: 'Recupera tu acceso', lede: 'Te enviaremos un código para que elijas una nueva contraseña.', action: 'Enviar código', alternate: '¿Recuerdas tu contraseña?', link: 'Volver a iniciar sesión' },
  verify: { title: 'Revisa tu correo', lede: 'Escribe el código de 6 dígitos que enviamos a', action: 'Confirmar código', hint: 'El código vence en 10 minutos. Si no lo encuentras, revisa la carpeta de spam.', resend: 'Enviar otro código', changeEmail: 'Usar otro correo' },
  newPassword: { title: 'Elige tu nueva contraseña', lede: 'Usarás esta contraseña la próxima vez que entres.', action: 'Guardar contraseña', complete: 'Tu contraseña está lista' },
  account: { title: 'Tu cuenta', lede: 'Administra tu acceso a AFCRtecnologia.', email: 'Correo verificado', method: 'Método de acceso', password: 'Correo y contraseña', google: 'Google', signOut: 'Cerrar sesión', store: 'Ir a la tienda', loading: 'Comprobando tu sesión…' },
  email: 'Correo electrónico',
  methodChange: {
    title: 'Cómo entras a tu cuenta',
    intro: 'Tienes un solo método de acceso activo. Puedes cambiarlo verificando tu correo.',
    toGoogle: 'Cambiar a Google',
    toPassword: 'Cambiar a correo y contraseña',
    passwordWarning: 'Al terminar, entrarás con tu correo y contraseña. Google dejará de permitir el acceso a esta cuenta.',
    googleWarning: 'Al terminar, entrarás con Google. Tu contraseña dejará de permitir el acceso a esta cuenta.',
    send: 'Enviar código de confirmación',
    verifyGoogle: 'Confirmar código',
    completePassword: 'Confirmar código y cambiar a contraseña',
    cancel: 'Cancelar cambio',
    back: 'Volver a mi cuenta',
    sent: 'Enviamos un código a tu correo verificado.',
    googleReady: 'Correo confirmado. Elige en Google la cuenta que usa este mismo correo para terminar el cambio.',
    continueGoogle: 'Continuar con Google',
    googleComplete: 'Ahora tu cuenta utiliza Google. El acceso con contraseña está desactivado.',
    passwordComplete: 'Ahora tu cuenta utiliza correo y contraseña. Google está desactivado. Inicia sesión para continuar.',
    sessionExpired: 'Tu sesión terminó o el método de acceso cambió. Vuelve a iniciar sesión.',
    wrongGoogle: 'Para cambiar el método, elige en Google la cuenta que usa el correo verificado de AFCRtecnologia.',
    emailUnavailable: 'No pudimos enviar el código. Tu método actual sigue activo. Inténtalo de nuevo en un minuto.',
    pending: 'El cambio se está procesando. Espera un momento antes de volver a intentarlo.',
    email: { subject: 'Confirma el cambio de acceso a AFCRtecnologia', title: 'Confirma tu cambio de acceso', body: 'Usa este código para cambiar tu método de acceso a' },
  },
  emailPlaceholder: 'tu@correo.com',
  password: 'Contraseña',
  newPasswordLabel: 'Nueva contraseña',
  confirmPassword: 'Confirmar contraseña',
  passwordHint: 'Usa al menos 12 caracteres, con mayúsculas, minúsculas y números.',
  showPassword: 'Mostrar contraseña',
  hidePassword: 'Ocultar contraseña',
  otp: 'Código de 6 dígitos',
  google: 'Continuar con Google',
  or: 'o con tu correo',
  forgot: 'Olvidé mi contraseña',
  wait: (seconds: number) => `Puedes reenviar en ${seconds} s`,
  working: 'Un momento…',
  confirmed: 'Correo confirmado. Tu cuenta está lista.',
  resent: 'Enviamos un nuevo código. Usa el más reciente.',
  passwordUpdated: 'Contraseña actualizada. Inicia sesión con tu nueva contraseña.',
  recoverySent: 'Si el correo corresponde a una cuenta, recibirás un código de recuperación.',
  unconfirmed: 'Confirma tu correo antes de entrar. Puedes solicitar un nuevo código aquí.',
  safety: 'Tu contraseña se mantiene oculta hasta que pulses el ojito.',
  emailMessage: {
    title: 'Tu código de verificación',
    body: 'Introduce este código en AFCRtecnologia para completar la solicitud.',
    expiry: 'El código tiene 6 dígitos y vence en 10 minutos. Utiliza solo el más reciente.',
    security: 'No compartas este código. Si no solicitaste esta acción, puedes ignorar este correo.',
    subjects: {
      confirmation: 'Confirma tu correo en AFCRtecnologia',
      recovery: 'Recupera tu acceso a AFCRtecnologia',
      magic_link: 'Tu código de acceso a AFCRtecnologia',
      email_change: 'Confirma tu cambio de correo',
      reauthentication: 'Verifica tu identidad en AFCRtecnologia',
    },
  },
  errors: {
    email: 'Escribe un correo válido.',
    password: 'La contraseña debe tener entre 12 y 72 caracteres, mayúsculas, minúsculas y números.',
    passwordRequired: 'Escribe tu contraseña.',
    mismatch: 'Las contraseñas no coinciden.',
    otp: 'Escribe los 6 dígitos del código.',
    expired: 'El código no es válido o ya venció. Revisa el último correo o solicita otro.',
    credentials: 'El correo o la contraseña no son correctos. Revisa los datos o recupera tu acceso.',
    rateLimit: 'Has realizado varios intentos. Espera unos minutos antes de volver a intentarlo.',
    network: 'No pudimos conectar. Revisa tu conexión e inténtalo de nuevo.',
    google: 'El acceso con Google no está disponible ahora. Inténtalo más tarde.',
    methodGoogle: 'Esta cuenta utiliza Google. Entra con Google para administrar tu método de acceso.',
    methodPassword: 'Esta cuenta utiliza correo y contraseña. Entra con tu contraseña para administrar tu acceso.',
    unavailable: 'No pudimos completar la solicitud. Inténtalo de nuevo en unos minutos.',
    config: 'El acceso a cuentas no está disponible ahora. Inténtalo más tarde.',
  },
} as const;
