export const storeCopy = {
 title:'Tienda online', lede:'MiniPcs y cámaras de seguridad. Elige tu equipo y prepara tu pedido con AFCRtecnologia.',
 categories:[{id:'minipcs',name:'MiniPcs',description:'Computación en formato compacto.'},{id:'security-cameras',name:'Cámaras de seguridad',description:'Equipos para tus espacios.'}] as const,
 categoryLabel:'Categorías', catalog:'Catálogo', cart:'Carrito', added:'Producto añadido a tu carrito.', add:'Añadir al carrito', outOfStock:'Sin stock', unavailable:'Producto no disponible', details:'Características', imagePending:'Foto de producto pendiente',
 loading:'Cargando productos', loadError:'No pudimos cargar los productos. Vuelve a intentarlo.', retry:'Volver a intentar',
 emptyTitle:'Estamos preparando esta selección.', emptyBody:'Los equipos aparecerán aquí cuando su disponibilidad, precio y fotografías estén confirmados.', emptyAction:'Consultar por un equipo',
 cartTitle:'Tu carrito', emptyCart:'Tu carrito está vacío.', emptyCartBody:'Elige un equipo del catálogo para preparar tu pedido.', checkout:'Finalizar pedido', continueShopping:'Seguir explorando', remove:'Quitar producto', quantity:'Cantidad', increase:'Aumentar cantidad', decrease:'Disminuir cantidad', close:'Cerrar carrito',
 subtotal:'Subtotal', shipping:'Envío', shippingPending:'A calcular', total:'Importe de productos', shippingNote:'El envío se coordina por separado. Su costo está pendiente de confirmar.', cartSaved:'Tu carrito se guarda en este dispositivo, también al iniciar sesión.',
};
export const checkoutCopy = {
 title:'Finaliza tu pedido', lede:'Tus equipos, tus datos y la forma de recibirlos. Todo en un mismo lugar.', identify:'Identifícate para continuar', accountNeeded:'Necesitas una cuenta para finalizar y seguir tu pedido. Tus productos seguirán en el carrito.',
 login:'Ya tengo cuenta', register:'Crear cuenta nueva', loginAction:'Ingresar y continuar', registerAction:'Crear cuenta y continuar', haveCode:'Ya tengo un código', forgot:'¿Olvidaste tu contraseña?',
 benefits:['Seguimiento del pedido','Guardar datos de envío','Historial de compras'], yourOrder:'Tu pedido', secure:'Tu cuenta y tus datos viajan por una conexión segura. Este paso no realiza ningún cobro.', loading:'Comprobando tu cuenta',
 steps:['Datos','Envío','Pago','Confirmación'], names:'Nombres', surnames:'Apellidos', mobile:'Celular', continue:'Continuar', back:'Volver', dataTitle:'¿Quién recibirá el pedido?', dataHint:'Usaremos estos datos para coordinar la entrega.',
 shippingTitle:'¿Cómo recibirás tu pedido?', lima:'Lima Metropolitana', limaBody:'Delivery hasta tu vivienda', provinces:'Provincias', provincesBody:'Recojo en un punto Urbano', district:'Distrito', selectDistrict:'Selecciona tu distrito', street:'Calle y número', reference:'Referencia', department:'Departamento', selectDepartment:'Selecciona tu departamento', pointsPending:'Puntos Urbano pendientes de cargar', pointsHint:'Elige otro departamento o vuelve cuando estén disponibles. Todavía no puedes confirmar un recojo aquí.', limaProvinces:'En Lima, esta modalidad corresponde a provincias fuera de Lima Metropolitana.', pickupPoint:'Punto de recojo',
 paymentTitle:'Revisa antes de confirmar', paymentNotice:'El cobro online aún no está integrado. MercadoPago o Stripe se incorporarán más adelante. Al confirmar, registramos tu pedido pendiente de pago.', confirm:'Confirmar pedido', confirming:'Registrando tu pedido', confirmed:'Pedido confirmado', orderNumber:'Número de pedido', deliveryConfirmed:'Coordinaremos contigo el costo y la entrega a tu vivienda. El pedido está pendiente de pago.', pickupConfirmed:'Te avisaremos cuando tu pedido esté listo para recoger. El pedido está pendiente de pago.', orders:'Mis pedidos', catalog:'Volver al catálogo', sessionExpired:'Tu sesión venció. Identifícate para continuar; tu carrito sigue guardado.', failed:'No pudimos registrar el pedido. Revisa tu conexión y vuelve a intentarlo.', invalid:'Revisa los productos y los datos de entrega antes de continuar.', priceChanged:'El precio o el stock cambió. Vuelve al carrito y actualiza los productos antes de confirmar.', saved:'Pedido registrado correctamente.',
 ordersTitle:'Tus pedidos', noOrders:'Aún no tienes pedidos.', orderPending:'Pendiente de pago', orderLoadError:'No pudimos cargar tus pedidos. Inténtalo de nuevo.', address:'Dirección de entrega', pickup:'Recojo en', editCart:'Editar carrito', invalidMobile:'Introduce un celular peruano de nueve dígitos que empiece con 9.', nameRequired:'Completa nombres y apellidos.',
};
